opac_proc/datastore/mongodb_connector.py
opac_proc/datastore/redis_queues.py
opac_proc/extractors/base.py
opac_proc/loaders/base.py
opac_proc/loaders/process.py
opac_proc/transformers/utils.py
opac_proc/web/views/home.py
thrift_clients/clients.py

ainda falta ajustar a interpolação nos loggers

Ajustes para landscape.io (parte 2)

---

am2opac.py

Durante o processo de importação da coleção brasil encontrei um traceback informando um erro no trecho de código corrigido aqui.
Ao ler o método percebi que existia um erro de digitação e fiz uma correção rápida. Se for necessário posso criar um issue para este PR.
**Caso de Teste:**
- Execute a importação da coleção SciELO Brasil.
- No `setup.py` setar `OPAC_PROC_COLLECTION = os.environ.get('OPAC_PROC_COLLECTION', 'scl')`
- Execute: `python am2opac.py`
- Validar se os dados foram importados corretamente

fix bulk method - Corrige erro de digitação de linha de código

---

requirements.txt

Reverts scieloorg/opac_proc#55
Erro no build: https://travis-ci.org/scieloorg/opac_proc/builds/200973485

Revert "Update rq-dashboard to 0.3.8"

---

opac_proc/web/config.py

Com a alteração da porta onde o serviço está sendo disponibilizado foi necessário alterar a configuração padrão para garantir o pleno funcionamento do app.

Corrige porta padrão para acesso ao articlemeta

---

opac_proc/transformers/tr_articles.py
opac_proc/web/templates/includes/page_header.html
opac_proc/web/templates/object_list/base.html
opac_proc/web/views/generics/list_views.py
opac_proc/web/views/transform/list_views.py

- mudança de tamanho de página (per page) com as opções: [10, 20, 50, 100, 500, 1000]
- notificação da quantidade de filas selecionadas (checkboxes)
- fix link da paginação que ignorava a querystring
- add botão de "refesh page"
- agora na transformação salvamos o campo de "data_model_version" para os artigos

features e ajustes nas listagens e salvando campo de "data_model_version" na tranformação

---

opac_proc/web/templates/macros/object_list.html
requirements.txt

the workaround:
To avoid the conversion of unicode fields (from ArticleMeta) to date/datetime objects
The definitive fix is done in the branch with partial processing

update requirement opac_schema to v2.40 and workaround

---

opac_proc/datastore/models.py
opac_proc/datastore/mongodb_connector.py
opac_proc/loaders/jobs.py
opac_proc/source_sync/differ.py
opac_proc/source_sync/differ_consumer_jobs.py
opac_proc/source_sync/differ_producer_jobs.py
opac_proc/web/templates/home.html
opac_proc/web/templates/rq_dashboard/dashboard.html

- fix Extract identifier data
- fix logger message level for db connections
- improvemnt: when deleting Load records also delete OPAC models records to keep it in sync
- improvemnt: `differ.apply_diff_record` now process lists of uuids instead of unefficient "selected > one" loop
- workaround: when collecting diff records from news | press releases.
- fix: typo confussing News with press releases
- improvement: @ home, diff table now highlights when have any records with yellow backgoud
- improvement: @ dashboard now we can collapse Queues and Workers tables

fixes processing diff (ETL) + ui improvements

---

opac_proc/core/assets.py
opac_proc/tests/test_assets.py

Alteração do `Asset. _extract_media()` para fazer a conversão.

Fix: conversão XML unicode para UTF-8 para gerar XML ElementTree

---

opac_proc/source_sync/ids_data_retriever.py
opac_proc/web/config.py

- substituindo coleta de identificadores da API Thrift com o adapter para consulta no Banco
- ajustes de processing date e parser de datatimes  somente quando necessário
- aumentando o prazo de dias (no passado) para coleta de identificadores, de 7 para 30 dias

processamento parcial - coleta de identificadores via DB

---

opac_proc/manage.py
opac_proc/source_sync/sched.py
opac_proc/web/accounts/templates/accounts/login.html
opac_proc/web/accounts/templates/accounts/register.html
opac_proc/web/accounts/templates/accounts/registration_disabled.html
opac_proc/web/accounts/templates/accounts/reset_password.html
opac_proc/web/accounts/templates/accounts/reset_with_token.html
opac_proc/web/accounts/templates/accounts/unconfirm_email.html

management commands:
- `python manage.py setup_idsync_scheduler` para instalar os schedulers
- `python manage.py clear_idsync_scheduler` para remover os schedulers
os comandos podem receber o parâmetro: `-m` ou `--model` para indicar o modelo. por padrão vai instalar/remover schedulers para todos os modelos: `collection`, `journal`, `issue`, `article`, `press_release` e `news`.

Schedulers para recuperação de identificadores

---

opac_proc/core/assets.py
opac_proc/tests/test_assets.py
opac_proc/web/config.py

Related to #325 e #326 
- Validação das extensões de ativos digitais para artigos em XML
- Validação `src`s de ativos digitais para artigos em HTML, preservando
links externos
- Correção do source path para PDFs para artigos em XML
- Ajustes nas normailizações dos paths dos ativos digitais de artigos
- Testes unitários

Ajustes na transformação de artigos no tratamento dos ativos digitais

---

opac_proc/core/logging.ini
opac_proc/core/sched.py
opac_proc/differs/consumer_sched.py
opac_proc/differs/process.py
opac_proc/differs/producer_sched.py
opac_proc/manage.py
opac_proc/source_sync/sched.py
opac_proc/utils.py
start_scheduler.sh

- movendo classe: `SyncScheduler` para core/sched.py
- `producer_sched.py` tem as classes especificas de cada scheduler que
producem a diff para cada fasse para cada modelo para cada ação
- `consumer_sched.py` tem as classes especificas de cada scheduler que
consomem a diff para cada fasse para cada modelo para cada ação
- adicionado no `manage.py` os comandos para setup e clear de schedulers
- fix na class differ.process@ProcessDiffersbase que apontava nos
caminhos errados para as task de consumo
- fix nas strings de cron, que não rodabam de 30 em 30, só no minuto 30
- add management commnads no `start_scheduler.sh` para fazer setup de
todos os schedulers quando iniciar o container

add schedulers para produzir e consumir registros de processamento parcial

---

opac_proc/core/sched.py
opac_proc/core/tasks.py
opac_proc/manage.py
opac_proc/web/config.py
start_scheduler.sh

- aumenta o timeout dos jobs nos schedulers de 180 seg para 2000 seg
- valor do timeout (em segundos) agora é configurável
- add de timout para os schedulers que geram os arquivos de catálogos (tinha sido ajustado só no spa-master)
- novo comando no manage.py `clear_and_setup_all_schedulers` para zerar e instalar todos os schedulers de uma vez. evitando assim que os jobs sejam registrados no redis mais de uma vez.

FIX: schedulers agendados multiplas vezes e add param timeout

---

Makefile
opac_proc/core/assets.py
opac_proc/tests/fixtures/1851-8265-scol-14-01-51.xml
opac_proc/tests/fixtures/article.json
opac_proc/tests/test_assets.py
opac_proc/transformers/tr_articles.py
opac_proc/web/config.py
requirements.txt

- Alteração no registro de artigos em XML e seus assets no SSM
- Alteração em `tr_articles` para utilizar a estrutura nova do AssetXML
- Criação de testes
- Ajuste na configuração padrão da geração do catálogo estático

 Reestruturação da classe AssetXML e ajuste em configuração (#349)

---

opac_proc/core/assets.py
opac_proc/tests/test_assets.py

`xlink:href` para links externos não devem ser substituídos.

Correção na transformação de artigos XML

---

Makefile
opac_proc/core/assets.py
opac_proc/tests/base.py
opac_proc/tests/test_assets.py
opac_proc/web/config.py

Corrige o problema reportado no OPAC (ver [@opac#1049](https://github.com/scieloorg/opac/issues/1049)).
- Ajustes no `AssetHTMLS._normalize_media_path()`
- Refatoração do código assets.py
- Melhorias nos testes do test_assets.py
- Melhorias nos comandos docker-compose no Makefile
No arquivo `core.assets.py`, classe `AssetHTMLS`
1. Verificar artigos versão HTML que contém HTMLs como ativo digital, como estão hoje. Ex:
- https://new.scielo.br/article/mioc/1997.v92n4/477-481/en/
Contém https://new.scielo.br/img/fbpe/mioc/v92n4/html/05fig1.htm, que está incorreta. A versão antiga (http://www.scielo.br/scielo.php?script=sci_arttext&pid=S0074-02761997000400005&lng=en&nrm=iso&tlng=en) o erro não ocorre
- https://new.scielo.br/article/acb/2002.v17n6/381-387/en/
Contém link para …

Correção na transformação de artigos HTML

---

opac_proc/core/assets.py
opac_proc/tests/test_assets.py

Correção de `Asset._is_valid_media_url()`
No `Asset._is_valid_media_url()` e no `TestAssetHTMLS`, nos testes para validar o método
Transformar um artigo em versão HTML contendo âncoras. Ex.: `S0074-02761997000500013`
Foram feitas correções na transformação de artigos HTML em #385. Esse erro corrige esse PR.
[@opac#1049](https://github.com/scieloorg/opac/issues/1049)
N/A

Correção na validação de URL na transformação de Artigo

---

Dockerfile
Dockerfile-dev
docker-compose-build.yml
docker-compose-dev.yml
docker-compose.yml
requirements.txt

- Atualização do mongoengine: 0.16.1 => 0.16.2
- Fixação da versão do redis por [incompatibilidade](https://github.com/rq/rq/issues/1014) da versão `0.12.0` do rq  com `redis >= 3.0`

Atualização da versão do mongoengine e fixação da versão do redis

---

opac_proc/extractors/ex_collections.py
opac_proc/extractors/source_clients/amapi_wrapper/custom_amapi_client.py

Altera a extração de coleção para, ao invés de recuperar todos os dados de coleção do AM para procurar uma na lista, recupera a coleção dada.
Pelo `ex_collections.py`, onde é feito um _for loop_ para obter uma coleção da lista retornada.
O seguinte job deve funcionar:
```
from opac_proc.extractors.jobs import task_extract_one_collection
task_extract_one_collection()
```
Pela interface, extrair a coleção no processo de ETL tbm deve funcionar.
N/A
Related to scieloorg/articles_meta/issues/155
N/A
N/A

Alteração na extração de dados de coleção

---

opac_proc/manage.py

- Alterado comando `setup_produce_differ_scheduler` no `manage.py` para
não enfileirar tarefas de diff produce para deleção de registros de artigos
- Criado comando `setup_produce_delete_article_differs` no `manage.py`
para enfileirar exclusivamente tarefas de diff produce de registros de
artigos, incluindo tarefas de deleção
Em `opac_proc/manage.py`, no comando `setup_produce_differ_scheduler`
- Executar o comando `python opac_proc/manage.py setup_produce_differ_scheduler`. Ele deve configurar todas as filas de produce no scheduler, exceto as filas de deleção de registros de artigos em todas as fases do ETL
- Executar o comando `python opac_proc/manage.py setup_produce_delete_article_differs`.  Ele deve configurar somente as filas de produce de deleção de registros de artigos no …

Retiradas tarefas de diff de deleção de registros de artigos

---

opac_proc/differs/base.py

Alterada consulta de uuids para produzir registros de differs de adição para evitar timeouts constantes nas consultas do Mongo.
Related to #419 .

Melhoria no processo de produção de registros de differs

---

opac_proc/extractors/source_clients/am_db/api_db_adapter.py

Retira a data de corte para recuperar os identificadores de periódicos.
Como o `processing_date` do periódico é reference ao cadastro na Title e este pode ocorrer meses antes da entrada dele para ingestão, o OPAC-PROC não consegue recuperá-lo e isso acaba gerando erro no processamento de artigos relacionados a ele.
Pela interface WEB, acessar os Identifiers > Issues > Processar > Todos os registros.
Deve ser possível recuperar os identificadores de todos os periódicos, independente do campo `processing_date`.
Como informação complementar, ocorre no processamento de artigos relacionados aos periódicos não processados a seguinte exceção:
`DoesNotExist: TransformIssue matching query does not exist.`
N/A

Retira data de corte para issues

---

opac_proc/transformers/tr_articles.py

Corrige campo `is_aop` do artigo na fase de transformação, que estava sendo informado como verdadeiro nos artigos ex-ahead ao invés dos aheads atuais.
Em `transformers/tr_article.py`, `ArticleTransformer.transform()` nos sets de parâmetros do Xylose.
Ao transformar um artigo Ahead of Print, o campo `is_aop` deve ser True. Para os ex-aheads, este campo não deve existir. O que indica que ele é um ex-ahead é o campo `aop_pid`.
No admin do site, no catálogo de artigos, o filtro de "É Ahead of Print?" retorna os ex-aheads ao invés dos aheads.
#418 
N/A
N/A

Corrige campo 'is_aop' que informava o ex-ahead ao invés do ahead

---

opac_proc/transformers/tr_journals.py

Corrige erro ao popular dados de study_areas e subject_categories. Os valores estão trocados.
opac_proc/transformers/tr_journals.py
N/A
N/A
https://github.com/scieloorg/opac/issues/1201
N/A

[opac] Erro ao popular dados de study_areas e subject_categories

---

opac_proc/loaders/jobs.py
opac_proc/loaders/lo_articles.py
opac_proc/web/views/load/list_views.py
requirements.txt

Ele resolve o problema da duplicidade de Ahead Of Print. Com a entrada de um ex-ahead em um fascículo regular, é necessário que a URL do AOP continue funcionando. Os url_segments do "issue" de ahead e do Ahead Of Print são usados na montagem da URL para o artigo e este PR grava esses dados no registro de ex-ahead. Para que o não haja duplicidade, o identifier e os registros de ETL são excluídos. Em detalhes, este PR:
- Atualiza o OPAC-SCHEMA para adicionar o campo de `aop_url_segs`, onde os url_segments do "issue" de ahead e do artigo AOP são mantidos
- Criado `ArticleLoader.prepare_aop_url_segs()` para a montagem do conteúdo do campo `aop_url_segs`
- Criado `ArticleLoader.remove_aop_records()` para a exclusão do identifier e sos registros de ETL do AOP
- Correção do filtro de PID na …

Resolve duplicidade de AOPs e acesso aos ex-AOPs pela url de AOP

---

opac_proc/manage.py

Nesse PR adiciona as task de atualizam os `press_release` e `news` no opac, assim os dados podem ser atualizados automaticamente junto com os processamentos de artigos
Analizando o arquivo `opac_proc/manager.py`
Rodando os comando utilizados para atualizar e processar as coleções 
```bash
$ python ./opac_proc/manage.py process_extract -f file_processa.txt
$ python ./opac_proc/manage.py process_transform -f file_processa.txt
$ python ./opac_proc/manage.py process_load -f file_processa.txt
```
scieloorg/opac#829

 Adicionando tasks para os 'press_release' e 'news' no manager.py

---

requirements.txt

Adicionando Versão da lib do redis usada pelo rq para a versao `redis==2.10.6`
o problema acontece com a versão mais nova da lib

adiconando versão do redis no requirements.txt

---

opac_proc/loaders/lo_news.py
opac_proc/transformers/tr_news.py

A URL da imagem de feeds do Blog SciELO já estavam sendo salvas na extração mas não enviadas para o site. Atualiza a base do OPAC para que essa URL esteja disponível.
Em `opac_proc/transformers/tr_news.py`, no método `transform()`
Transformar e carregar todas as `News`. A URL vinda do feed em `media_content` deve estar nos registros de `News` do OPAC.
Para exibição das imagens dos feeds do Blog SciELO é necessário que a base do OPAC seja alimentada com os dados processados pelo PROC. Também é necessária alteração do OPAC para a imagem ser exibida.
N/A.
scieloorg/opac/issues/318
Nenhuma.

Processa URL da imagem de feeds do Blog SciELO

---

requirements.txt

esse PR atualiza a versao do packtools para incorporar as novas alteração do XSLT
https://github.com/scieloorg/packtools/commit/3524cfbefb8e6d676c3448f24b47fdf92163b85e
pelo `requirements.txt`
apos atualizar o codigo e reconstruir a docker ou seu ambiente local, rodas os teste ou reprocessar alguns documentos atraves da interface web do opac
scieloorg/opac#1123

Atualizacao da verção do packtools scieloorg/opac#1123

---

opac_proc/loaders/lo_journals.py
opac_proc/web/views/load/list_views.py

Corrige a carga de periódicos sem fascículos para o site. As seguintes alterações foram feitas:
- Ocorria uma exceção caso o periódico não tivesse nenhum fascículo vinculado a ele. Com isso, o periódico não era carregado no site. A correção permite a carga desses periódicos para o site.
- Configura o periódico para não-público quando não houver fascículos. Assim, ele não aparece na página mas permite, por exemplo, cadastrar páginas secundárias para o periódico.
- O parâmetro `is_public` configurado no Admin do site não é sobrescrito.
Também há uma correção no filtro da listagem de periódicos carregados (Load).
Em `opac_proc/loaders/lo_journals.py`, nos métodos `prepare_collection()` e `prepare_is_public()` de `JournalLoader `
- Pela interface do PROC, carregar um periódico sem fascículos. …

Corrige a carga de periódicos sem fascículos para o site

---

opac_proc/core/assets.py
opac_proc/tests/test_assets.py
opac_proc/transformers/tr_articles.py

Retira a geração de HTML de artigos XML, bem como o registro das informações desse resultado. Além disso, toda a lógica que implementa a manutenção do conteúdo HTML no SSM passa a ser desnecessária e, por isso, também foi retirada. Por fim, os testes relacionados também foram removidos.
Com este PR, espera-se que a transformação de artigos passe a levar menos tempo e que recursos em disco não sejam desperdiçados sem razão.
Em `opac_proc/transformers/tr_articles.py`.
Para novos artigos XML:
1. Transformar um artigo
2. Não devem constar erros no Dashboard das tarefas
3. O documento na collection `t_article` não deve conter o campo `htmls`
4. O XML do artigo e seus ativos digitais devem ser encontrados no SSM mas o HTML não
Para artigos já existentes:
1. Transformar um artigo
2. Não devem …

Retira geração de HTML na transformação

---

requirements.txt

Atualiza versão do Legendarium que corrige a url segment de fascículos com volume alfanumérico.
Em `requirements.txt`
1. Acesse __Load > Issue__ na interface WEB do PROC
2. Procure um fascículo com volume alfanumérico. Ex: PID `1516-891320010005` na coleção BR
3. Selecione o fascículo e reprocesse-o.
4. Certifique-se que nenhum erro foi registrado no processamento deste fascículo.
5. Acesse __OPAC > Issue__
6. Procure um fascículo reprocessado.
7. Verifique se o campo `url_segment` foi registrado com o volume de forma correta.
Conforme descrito no ticket scieloorg/opac/issues/1342, os fascículos com volume alfanuméricos estão registrados com o `url_segment` incorreto.
N/A
#479, scieloorg/opac/issues/1342
Nenhuma.

Atualiza versão do Legendarium p/ correção de volumes alfanuméricos

---

opac_proc/core/assets.py
opac_proc/tests/test_assets.py
opac_proc/transformers/tr_articles.py

Para que o site identifique quais idiomas o artigo possui, é necessário que o processamento informe no registro de artigo os idiomas disponíveis no XML.
Em `opac_proc/core/assets.py`.
1. Selecione um artigo XML que o registro na collection do MongoDB `t_article` não tenha o campo `htmls` ou apague este campo de um registro.
2. Acesse a interface do OPAC-PROC, em Transform > Articles
3. Processe a transformação do artigo selecionado
4. Verifique se a transformação foi executada com sucesso
5. O campo `htmls` no registro deste artigo deve estar com os idiomas disponíveis no XML
Este campo foi retirado com a renderização dos HTMLs no processo de transformação, pois a partir da versão 3 do site os HTMLs são renderizados pela aplicação OPAC em tempo real (no acesso ao artigo). Porém, para que …

Adiciona os idiomas de HTMLs produzidos através do XML de artigo

---

opac_proc/web/static/js/filters_toolbar.js
opac_proc/web/views/generics/list_views.py

Os filtros de subcampos de campo `metadata` em todas as listagens não estavam funcionando (datas, processamento completo e reprocessar). Além de alterar o `list_view` para fazer corretamente o filtro pelo mongoengine, foi alterada a barra de filtro em JS para obter corretamente nomes de campos com `.`.
Em `opac_proc/web/static/js/filters_toolbar.js`
- Acesse as listagens de extração, transformação ou carga
- Utilize os filtros de conteúdos por data da última alteração, processamento completo e reprocessar e todos devem funcionar corretamente.
- Utilize os outros filtros string presentes nas listagens e todos devem permanecer funcionando.
Este erro foi encontrado em situação de necessidade de reprocessamento de conteúdo e é essencial para fazê-lo de forma mais rápida.
N/A
-
Nenhuma.

Corrige filtro das listagens

---

requirements.txt

Altera a versão do opac_schema para receber mais do que um e-mail
No arquivo de **requirements.txt**
Iniciando o opac-proc e realizando a fase de **extract, transform e load** da entidade Journal.
Foi realizado teste manual localmente e a fase de carga está funcionando corretamente
Foi alterado o dado de forma manual no periódico Physis: 
https://github.com/scieloorg/opac_proc/issues/523
N/A

Altera a versão do opac_schema para receber mais do que um e-mail

---

requirements.txt

Atualiza versão do opac_schema para corrigir o problema do campo de email do editor, que está sendo usado como campo texto.
Em `requirements.txt`
- Busque um periódico que tenha o campo de email do editor com mais de 1 endereço de email separado por ponto e vírgula ou barra.
Estes periódicos não estavam sendo atualizados no OPAC por conta da validação de emails que existia no Opac Schema. O campo foi transformado em texto e a validação não será mais feita.
n/a
#523 
Nenhuma.

Atualiza versão do OPAC_Schema da 2.52 para 2.54

---

opac_proc/loaders/base.py
requirements.txt

Este PR garante que, ao carregar os artigos transformados para o site, obtenha sempre o último registro transformado. Os registros são ordenados pela data de atualização do registro.
Commit 7f370f1
Com um fascículo de periódico com atualização de seções:
- Insira na scilista o acrônimo do periódico e o fascículo
- Execute o comando `python opac_proc/manage.py process_extract -f data/scilista.lst` e verifique que nenhum erro ocorreu no dashboard da interface WEB em `/dashboard`
- Execute o comando `python opac_proc/manage.py process_transform -f data/scilista.lst` e verifique que nenhum erro ocorreu no dashboard
- Execute o comando `python opac_proc/manage.py process_load -f data/scilista.lst` e verifique que nenhum erro ocorreu no dashboard
n/a
Quando aplicável e se fizer possível …

Altera Load do site p/ obter último registro de artigo transformado
