scieloorg/opac_proc

- am2opac.py
- requirements.txt
- thrift_clients/articlemeta.thrift
Atividades realizadas: 
* Atualizado o thrift file
* Adicionado o idioma do resumo no modelo **Article** 
* Adicionado um SIGINT no Pool para que seja possível matar todos os processos
> Abs lang and kill process

- am2opac.py
* Esse PR adiciona todos os idiomas do **Resumo** e **Texto** no atributo **languages** do artigo.
> Adicionando todos os idiomas no atributo languages do artigo.

- am2opac.py
- config.py
- requirements.txt
- thrift_clients/articlemeta.thrift
- thrift_clients/clients.py
- utils.py
Ajuste para atender ao Tk https://github.com/scieloorg/opac/issues/302 do OPAC.
> Atualizado o Thrift file do article meta adicionado os índices e métricas na coleção e nos periódicos

- opac_proc/extractors/ex_collections.py
- opac_proc/loaders/lo_collections.py
- opac_proc/loaders/lo_journals.py
- opac_proc/transformers/tr_collections.py
- opac_proc/web/config.py
> fixes na extração de metricas da coleção

- opac_proc/datastore/models.py
- opac_proc/extractors/ex_press_releases.py
- opac_proc/extractors/jobs.py
- opac_proc/loaders/jobs.py
- opac_proc/loaders/lo_journals.py
- opac_proc/loaders/lo_press_releases.py
- opac_proc/loaders/process.py
- opac_proc/transformers/base.py
- opac_proc/transformers/jobs.py
- opac_proc/transformers/process.py
- opac_proc/transformers/tr_press_releases.py
- opac_proc/web/templates/home.html
- opac_proc/web/templates/includes/nav.html
- opac_proc/web/urls.py
- opac_proc/web/views/extract/list_views.py
- opac_proc/web/views/generics/list_views.py
- opac_proc/web/views/home.py
- opac_proc/web/views/load/detail_views.py
- opac_proc/web/views/load/list_views.py
- opac_proc/web/views/opac/list_views.py
- revisão e ajustes no processo ETL dos PRs
- fix de importação duplicada
- fix de importação limitada a 1 pr por feed
> LOAD Press Releases e ajustes

- opac_proc/datastore/models.py
- opac_proc/datastore/redis_queues.py
- opac_proc/extractors/ex_news.py
- opac_proc/extractors/jobs.py
- opac_proc/extractors/process.py
- opac_proc/loaders/jobs.py
- opac_proc/loaders/lo_journals.py
- opac_proc/loaders/lo_news.py
- opac_proc/loaders/process.py
- opac_proc/transformers/jobs.py
- opac_proc/transformers/process.py
- opac_proc/transformers/tr_news.py
- opac_proc/web/config.py
- opac_proc/web/templates/home.html
- opac_proc/web/templates/includes/nav.html
- opac_proc/web/urls.py
- opac_proc/web/views/extract/detail_views.py
- opac_proc/web/views/extract/list_views.py
- opac_proc/web/views/generics/list_views.py
- opac_proc/web/views/home.py
- opac_proc/web/views/load/detail_views.py
- opac_proc/web/views/load/list_views.py
- opac_proc/web/views/opac/list_views.py
- opac_proc/web/views/transform/detail_views.py
- opac_proc/web/views/transform/list_views.py
- start_worker.sh
> etl noticias

- opac_proc/extractors/jobs.py
> Corrige a tarefa de extração de 1 artigo

- opac_proc/extractors/ex_articles.py
- opac_proc/extractors/source_clients/thrift/am_clients.py
- opac_proc/web/config.py
> Incluir a opção de extração de artigo com "body"

- opac_proc/transformers/tr_articles.py
> Ajustado bucket name e idioma para coleta dos pdfs

- opac_proc/core/asset_handler.py
- opac_proc/transformers/tr_articles.py
- requirements.txt
Fixes https://github.com/scieloorg/opac_proc/issues/80
> Garantindo a unicidade do asset no processamento dos PDFs.

- opac_proc/core/assets.py
- opac_proc/core/html_generator.py
- opac_proc/core/ssm_handler.py
- opac_proc/transformers/tr_articles.py
Correção para garantir que esta sendo depositado no SSM os ativos como bytes sem qualquer codificação e ajustando a checagem da existência das imagens.
> Correção de encoding e duplicidade no SSM.

- Dockerfile
- Dockerfile-dev
- opac_proc/core/process.py
- opac_proc/datastore/redis_queues.py
- opac_proc/extractors/jobs.py
- opac_proc/extractors/process.py
- opac_proc/loaders/jobs.py
- opac_proc/loaders/process.py
- opac_proc/transformers/jobs.py
- opac_proc/transformers/process.py
- opac_proc/web/views/extract/list_views.py
- opac_proc/web/views/generics/list_views.py
- opac_proc/web/views/load/list_views.py
- opac_proc/web/views/opac/list_views.py
- opac_proc/web/views/transform/list_views.py
- ajustes de otimização nos dockerfiles segundo recomendação do `www.fromlatest.io`
- fix parâmetros: `RQueues.get_queue(...)`
> Refactor da classe Process e dos modulos jobs.py

- opac_proc/core/assets.py
Correção para o HTML do legado.
> Ajuste para obter o html no idioma original do artigo e transformando para bytes quando o html é unicode

- opac_proc/core/assets.py
@jfunez não foi possível utilizar o uso do template, por termos que a obrigatoriedade de utilizar algum encode, como no SSM desejamos salvar sempre os bytes resolvi utilizar somente a interpolação.
> Envelop html version

- opac_proc/core/assets.py
Resolve erro em 5087 artigos do legado.
> Ajuste de path para imagens com 'fbpe' no path

- opac_proc/core/assets.py
- opac_proc/core/templates/article.html
- opac_proc/core/utils.py
- opac_proc/web/config.py
- requirements.txt
@jfunez ainda está em WIP por não conseguir testar no **opac_proc**, devido a latência na rede ao utilizar a VPN.
> Correções no artigo na versão HTML.

- opac_proc/loaders/base.py
- opac_proc/loaders/lo_issues.py
- opac_proc/transformers/jobs.py
- opac_proc/transformers/tr_issues.py
- opac_proc/web/views/opac/list_views.py
- opac_proc/web/views/transform/list_views.py
- Ajustes do issue.type -> volume_issue, outdated_ahead, ahead, etc
- ajuste na filtragem das listagens da base OPAC;
- fix; job de update de issues (transform) estava bugado;
> Ajustes tranform e load de issues (issue.type) e outros fixes

- opac_proc/web/static/js/actions_toolbar.js
- opac_proc/web/templates/object_list/base.html
- opac_proc/web/templates/object_list/includes/actions_toolbar.html
- opac_proc/web/views/generics/list_views.py
- opac_proc/web/views/transform/list_views.py
> Ações custom genéricas e botão de reprocessar só os artigos XML

- opac_proc/extractors/ex_journals.py
- requirements.txt
no novo método: `get_current_metrics(issn)`
FIX: #179
> 179 - Ajustar coleta de dados: h5m5 usando novas funções da lib

- opac_proc/core/assets.py
> trocar caminho das imagens no html do artigo: de url absoluta para path absoluto

- opac_proc/loaders/lo_issues.py
- opac_proc/transformers/tr_issues.py
- requirements.txt
**Pendente:**
atualização do xylose com a nova property: Issue.assets_code
> ajuste novo campo: Issue.assets_code

- opac_proc/transformers/tr_articles.py
- requirements.txt
Esse PR conclui mais alguns itens do tk https://github.com/scieloorg/opac/issues/656
> Adicionando Type, Publication Date e Keywords no modelo de article para metatags.

- opac_proc/loaders/lo_articles.py
- opac_proc/transformers/tr_articles.py
- requirements.txt
Referente ao ticket: https://github.com/scieloorg/opac/issues/656
> Lo article with metatags keywords type pubication date

- requirements.txt
Referente ao bug: https://github.com/scieloorg/opac/issues/562
> Resolve erro de cadastro de algumas seções dos artigos.

- opac_proc/core/assets.py
- opac_proc/transformers/tr_issues.py
- opac_proc/web/config.py
Fix: https://github.com/scieloorg/opac/issues/807
> From str order to int order

- opac_proc/loaders/lo_articles.py
- opac_proc/transformers/tr_articles.py
- opac_proc/web/config.py
- requirements.txt
* Adiciona novas extensões para coleta de ativos
* Atualiza o opac_schema
* Adiciona na transformação as traduções do resumo
> Ref opac 866

- opac_proc/loaders/lo_articles.py
> Adiciona o resumo na fase de load

- opac_proc/manage.py
Fixes: https://github.com/scieloorg/opac_proc/issues/262
> Adicionando a capacidade de processamento através do manage.py

- opac_proc/manage.py
Corrigi o command line para processo de load.
> Fix load process

- opac_proc/loaders/lo_journals.py
- opac_proc/manage.py
- opac_proc/transformers/tr_journals.py
- requirements.txt
Não é mais um **WIP**. 
Pode avaliar!
> Add editor email

- opac_proc/manage.py
- requirements.txt
* Adicionado o [articlemetaapi](https://github.com/scieloorg/articlemetaapi/tree/master/articlemeta) como dependência
* Adiciona a opção de realizar o processamento com os acrônimos.
> Adiciona a capacidade de processar via manage.py com acrônimo

- opac_proc/manage.py
- requirements.txt
Fixes #287.
Atividade não tem teste automatizado, porém houve vários teste manuais de utilização do novo recurso.
> Tk287 - Adiciona a capacidade de processar utilizando o acrônimo e o label do fascículo

- opac_proc/manage.py
> Corrigi os pids para uuid na fase de load

- opac_proc/extractors/jobs.py
- opac_proc/extractors/source_clients/amapi_wrapper/custom_amapi_client.py
- opac_proc/manage.py
- opac_proc/source_sync/ids_data_retriever.py
- opac_proc/source_sync/ids_data_retriever_jobs.py
- opac_proc/source_sync/utils.py
- opac_proc/web/config.py
- requirements.txt
* Necessário realizar alguns testes para manuais.
> WIP: Adiciona a capacidade de realizar o processamento cli (Acrônimo, ISSN e scilista.lst)

- opac_proc/manage.py
* Corrigi a ordem do param stage.
> Corrigi a ordem dos params na função process_issn_issue e process_issn_article

- Dockerfile
- Dockerfile-dev
- docker-compose-build.yml
- docker-compose-dev.yml
- docker-compose.yml
- opac_proc/core/jobs.py
- opac_proc/core/tasks.py
- opac_proc/manage.py
- opac_proc/source_sync/utils.py
- opac_proc/tests/test_home.py
- opac_proc/tests/test_source_sync.py
- opac_proc/web/config.py
- opac_proc/web/urls.py
- opac_proc/web/views/home.py
- requirements.txt
- start_scheduler.sh
- start_worker.sh
Fixes #308 
- Criação de endpoint para consulta do static_pdf_files.txt, static_html_files.txt e static_xml_files.txt
- Adicionado Scheduler
- Criação de tasks para geração dos catálogos estáticos
> Add endpoint e scheduler p/ catálogos de estáticos

- opac_proc/loaders/lo_articles.py
- opac_proc/transformers/tr_articles.py
- requirements.txt
> Adiciona o aop_pid, atualiza o OPAC_SCHEMA e adicionar o aop_pid no load.

- requirements.txt
release info: https://github.com/pallets/flask/releases/tag/0.12.4
> FIX: flask version marked as unsecure - upgrade it to v0.12.4

- opac_proc/differs/consumer_sched.py
👉  https://crontab.guru/#0,30_0-23_*_*_1,4
> mudando crons do Load (C, J, I, A) para segundas e quintas

- opac_proc/extractors/ex_collections.py
- opac_proc/web/config.py
Ajuste que deve ser realizado na instância de SPA.
Referente ao ticket: https://github.com/scieloorg/opac/issues/1023
> Ajusta os totais dos periódico para coletar somente os ativos.

- requirements.txt
Atualiza as seguintes dependências do projeto:
* Mongoengine
* RQ (que corrige a incompatibilidade com a versão 3 do Redis)
* Requests
* Prometheus-client
No requirements.txt
Extrair algum artigo já testaria as dependências.
N/A
N/A
N/A
N/A
> Atualiza requirements

- requirements.txt
Atualiza com packtools 2.4
Corrige a geração de HTML:
- apresentação de afiliação 
- apresentação de label de correspondência
requirements.txt
Verificar nos tickets mencionados abaixo os XML em que estas situações acontecem.
Fazer a etapa de Transformação do XML e verificar o HTML gerado.
N/A
https://github.com/scieloorg/opac/issues/992
https://github.com/scieloorg/opac/issues/993
N/A
> Atualização de packtools 2.4
